source "http://rubygems.org"

# Will automatically pull in this gem and all its
# dependencies specified in the gemspec
gem "yaram", :path => File.expand_path("../..", __FILE__)
gem "yaram-mongodb", :path => File.expand_path("..", __FILE__)

gemspec

group :test do
  gem 'rspec', '~>2.2.0'
end