source "http://rubygems.org"

# Will automatically pull in this gem and all its
# dependencies specified in the gemspec
gem "yaram-crypto", :path => File.expand_path("..", __FILE__), :require => "yaram/crypto"
gem "yaram", :path => File.expand_path("../..", __FILE__)

gem "ox", "~>1.2.7"

gemspec

group :test do
  gem 'rspec', '~>2.2.0'
end